### PR TITLE
Make Cocoa code compile

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by darrenstarr** [comment]
NoSami, I appreciate the pull request, but ever since Apple made it impossible for me to install XCode on my machines (I have old Macs which can't run recent MacOS versions), I have no ability to test. Can you  verify the code actually runs before I merge this?

**Comment by nosami** [comment]
@darrenstarr sure - works great... I just want to try and run this command without SSH now.

image

**Comment by darrenstarr** [comment]
Fantastic... thanks!

**Comment by nosami** [comment]
@darrenstarr did you decide on a license for this?

**Comment by nosami** [comment]
Never mind. I see it's MIT licensed - nice!

**Pull request merged**
